FLAGS = -std=c++23 -Wall -Wextra -Wpedantic -Wuninitialized -Wshadow \
		-Wmost -Wconversion -g -I../../../vendor/ -I../../../../../vendor \
		-DFMT_HEADER_ONLY

all:
	clang++ $(FLAGS) main.cpp -o entity_id_conflict.exe && ./entity_id_conflict.exe 