FLAGS = -std=c++2a -Wall -Wextra -Wpedantic -Wuninitialized -Wshadow \
                -Wconversion -g 

all:
	clang++ $(FLAGS) -I../../vendor/ main.cpp -o styling_integration_test.exe && ./styling_integration_test.exe 