FLAGS = -std=c++23 -Wall -Wextra -Wpedantic -Wuninitialized -Wshadow \
		 -Wconversion -g -I../../../vendor/ -I../../../../../vendor

all:
	clang++ $(FLAGS) main.cpp -o render_batching.exe && ./render_batching.exe
