include ../../common.mk
FLAGS = -std=c++23 -Wall -Wextra -Wpedantic -Wuninitialized -Wshadow \
		-Wmost -Wconversion -g 

all:
	clang++ $(FLAGS) main.cpp -o $(OUT)/simple_system.exe && $(OUT)/simple_system.exe
